@url_base = http://localhost:5003/api/item
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtIiwiZXhwIjoxNzUwMTA5MjQxfQ.I_7IvZFE6OYaMHgIFQtB552B5KznJjhoph5Jp4T_pwQ

### Cadastrar Itens
POST {{url_base}}/cadastrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtQGFkbS5jb20iLCJleHAiOjE3NTAxMTg0OTl9.WLKGmQTyRDjvwVBFV3Y0mlVM-dZjBoXenInb_WO8WBg
Content-Type: application/json

{
    "nome" : "Item 2",
    "categoriaId" : 1
}

### Listar Itens
GET {{url_base}}/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtQGFkbS5jb20iLCJleHAiOjE3NTAxMTg0OTl9.WLKGmQTyRDjvwVBFV3Y0mlVM-dZjBoXenInb_WO8WBg