@url_base = http://localhost:5003/api/usuario

### Cadastrar usuário
POST {{url_base}}/cadastrar
Content-Type: application/json

{
    "email" : "adm@adm.com",
    "senha" : "123"
}

### Login
POST {{url_base}}/login
Content-Type: application/json

{
    "email" : "adm@adm.com",
    "senha" : "123"
}

### Listar usuários
GET {{url_base}}/listar